### ISSUE TITLE
CloudFront alerts

### ISSUE THREAD

**Issue by Andrey9kin** [FivexL/base-infra-release#1]
The idea is to setup CloudWatch alerts to see if we are getting too many downloads, i.e. avoid denial of wallet attack 

See more here https://summitroute.com/blog/2020/06/08/denial_of_wallet_attacks_on_aws/ and here https://www.lastweekinaws.com/podcast/aws-morning-brief/whiteboard-confessional-the-curious-case-of-the-9000-aws-bill-increase/

**Comment by cageyv** [comment]
CloudFront releases.fivexl.io BytesDownloaded is higher than 100Mb/min
CloudFront releases.fivexl.io Requests is higher than 10000/min
Values can be changed later.
