### ISSUE TITLE
Lambda to update index.html

### ISSUE THREAD

**Issue by Andrey9kin** [FivexL/base-infra-release#3]

**Comment by cageyv** [comment]
Need to create:
 - Lambda Role with S3 file list access and write to index.html files
 - S3 trigger for run Lambda when new object will appear in S3 bucket. Maybe with Suffix .zip , .sha256 
 - Lambda code:
   - read bucket name from event.Records[0].s3.bucket.name
   - try s3.getObject
   - get all Objects patch 
   - start generate and PUT index.html in every folder in S3 
   - Maybe do in one loop scan folder until end , generate and put index.html
 - terraform lambda deployment as code
