### ISSUE TITLE
Analyzer of downloads

### ISSUE THREAD

**Issue by Andrey9kin** [FivexL/base-infra-release#4]
We want to know how often/how many our tools are being downloaded so we need to find a way to have a stats

Possible options - cloudfront logs, s3 access logs, CloudTrail data events

**Comment by cageyv** [comment]
In AWS Console have "[CloudFront Popular Objects Report](https://console.aws.amazon.com/cloudfront/home?region=eu-central-1#popular_urls:)" 
"The Amazon CloudFront console can display a list of the 50 most popular objects for a distribution during a specified date range in the previous 60 days."
If we want to know more information i think we need querying Amazon CloudFront Logs with [Athena](https://docs.aws.amazon.com/athena/latest/ug/cloudfront-logs.html) or some Lamba code

@Andrey9kin 60 days and top 50 in console is enough? or we need more info and use this info somewhere else?

**Comment by Andrey9kin** [comment]
@cageyv yes. that would do. Thanks for digging into it
